name: Hola Mundo

on: [push]

jobs:
    hello_job:
        runs-on: ubuntu-latest

        steps:
            - name: Imprimir Mensaje
              run: echo "Hola mundo desde GitHub Actions!"